### PR TITLE
automation: Load extra kernel-modules to support CentOS Stream 9

### LINKED ISSUE #47: Fails to run on CentOS stream 9 (due to selinux policy)
While running the the library on CentOS stream 9 with SELinux enforcing, it fails to load kernel-modules (implicitly).

Test log:
```
=== RUN   TestConfig
    config_test.go:85: 
        	Error Trace:	config_test.go:85
        	            				config_test.go:67
        	            				config.go:31
        	            				config_test.go:36
        	Error:      	Received unexpected error:
        	            	failed to execute /usr/sbin/nft nft -j -f /tmp/spoofcheck-747880379: exit status 1 stdout:'' stderr:'internal:0:0-0: Error: Could not process rule: No such file or directory
        	            	
        	            	'
        	Test:       	TestConfig
--- FAIL: TestConfig (0.03s)
```

Journal:
```
SELinux is preventing /usr/sbin/nft from module_request access on the system labeled kernel_t.

*****  Plugin catchall_boolean (89.3 confidence) suggests   ******************

If you want to allow domain to kernel load modules
Then you must tell SELinux about this by enabling the 'domain_kernel_load_modules' boolean.

Do
setsebool -P domain_kernel_load_modules 1

*****  Plugin catchall (11.6 confidence) suggests   **************************

If you believe that nft should be allowed module_request access on system labeled kernel_t by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'nft' --raw | audit2allow -M my-nft
# semodule -X 300 -i my-nft.pp
```

EDIT: Fixed the description of the problem. It has nothing to do with `/tmp` folder, but with the need to load kmod in a lazy manner by `nft`.

### PR DESCRIPTION
**Pull request by EdDev**
When running the tests on CentOS Stream 9, there is a need to load two new kmods on the host that runs the tests (as the container in which the tests are running has no permission to load a kmod).

To preserve the ability to run on older hosts, the `nft_meta_bridge` kmod is not strictly required (as it is not available on older kernels).

Fixes: #47

### CODE REVIEW

File: automation/run-tests.sh [hunk 1]
```diff
@@ -86,6 +86,8 @@ if [ -n "${OPT_ITEST}" ]; then
     # Manually load `nft_masq` kmod on the host to support NAT definitions.
     # The container is unable to load a kmod (usually done by `nft` automatically).
     sudo modprobe nft_masq
+    sudo modprobe nft_counter
+    sudo modprobe nft_meta_bridge | true
```
Comment (qinqon) [inline automation/run-tests.sh:90]: Install the module if it's present on the system, this way errors caused by other means will be found.

**Review by qinqon — CHANGES_REQUESTED** [review]

File: automation/run-tests.sh (hunk 1 above)
Comment (EdDev) [reply automation/run-tests.sh:90]: In order to implement that, there will be a need to add enough logic to make this cumbersome.
I am also not sure if the locations are the same on all distributions, which may complicate this even further.

I am not convinced this is required at this stage. If we will start seeing such issues, we will need to consider a solution.
The existing error (e.g. `modprobe: FATAL: Module nft_meta_bridge not found in directory /lib/modules/4.18.0-425.10.1.el8_7.x86_64`) should provide enough information on why it does not work.

Comment (qinqon) [reply automation/run-tests.sh:90]: Well is just a matter of doing something like 
```bash
if lsmod |grep nft_meta_bridge -q; then
    sudo modprobe nft_meta_bridge
fi
```

**Review by qinqon — APPROVED** [review]
doing `|true` is enough at least the error message is there

File: automation/run-tests.sh (hunk 1 above)
Comment (EdDev) [reply automation/run-tests.sh:90]: The problem is that this will work on old kernels where this new kmod does not exists anyway.
But on new kernels, where we do need to load it, it will not work because the kmod is not loaded yet (which `lsmod` reports) and therefore we will not load it (that is the condition).

In any solution, there will be a need to check about the kernel version to determine if we need the kmod or not. But maybe there are other options I could not think about yet.
